name: CI - Push Artifact Registry

on: 
  push:
    branches:
    - devops-migration
  pull_request:
    branches:
    - devops-migration

env:
  REGISTRY: us-west1-docker.pkg.dev
  IMAGE_NAME: ${{ github.repository }}
  PROJECT_ID: opt-74-backcountry-gcp-mig
  GAR_USERNAME: docker-pusher@opt-74-backcountry-gcp-mig.iam.gserviceaccount.com
  GAR_REPOSITORY: us-west1-docker.pkg.dev/opt-74-backcountry-gcp-mig/fulfillment
  
permissions:
  contents: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  build-and-push-to-gcr:
    name: Build & push
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GAR_WIP }}
          service_account: ${{ secrets.SA }}
          access_token_lifetime: 300s

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
             ${{ env.GAR_REPOSITORY }}/${{env.IMAGE_NAME}}:${{ steps.get-tag.outputs.short_ref }}
             ${{ env.GAR_REPOSITORY }}/${{env.IMAGE_NAME}}:latest